"""Sync all paper figures into paperinfra_all_charts/ + regenerate all_paper_charts.md.

Mirrors each `analysis/paper/results/part_{1,2,3}/figures/` dir into
`analysis/exploratory/paperinfra_all_charts/figures/part_{1,2,3}/` and rewrites
`all_paper_charts.md`. Chart order matches `paper/results/results.md`;
unknown PNGs (figures present in figures/ but not in CHART_ORDER) are
appended at the end of their part. Run after any paper figure update.
"""

from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PAPER_RESULTS = ROOT / "analysis" / "paper" / "results"
HERE = Path(__file__).resolve().parent
DEST = HERE / "figures"
MD_PATH = HERE / "all_paper_charts.md"

PARTS: tuple[tuple[str, str], ...] = (
    ("part_1", "Part 1 — Scale, Convergence, Growth"),
    ("part_2", "Part 2 — Characterization"),
    ("part_3", "Part 3 — Action"),
)

# Canonical chart order per part, matching paper/results/results.md.
CHART_ORDER: dict[str, list[str]] = {
    "part_1": [
        "convergence.png",
        "convergence_configs.png",
        "overview.png",
        "temporal_trend.png",
        "temporal_tables.png",
    ],
    "part_2": [
        "phys_info_divide.png",
        "job_zone_violin.png",
        "ska_skills.png",
        "ska_knowledge_abilities.png",
        "gwa_exposure.png",
        "major_categories.png",
    ],
    "part_3": [
        "conv_confirmed_ceiling_gap.png",
        "tech_commodities.png",
        "risk_score_5f.png",
        "intensity_anchor_fulleco.png",
    ],
}

# Charts to skip even if present in the source figures/ dir.
# phys_zone_{stacked,faceted} are bonus part_2 outputs not in results.md;
# the appendix carries the canonical version of phys_zone_faceted.
# ska_levels.png is the old combined SKA chart; it's been split into
# ska_skills.png and ska_knowledge_abilities.png.
SKIP: set[str] = {
    "temporal_deltas.png",
    "phys_zone_stacked.png",
    "phys_zone_faceted.png",
    "ska_levels.png",
}


def _ordered(part: str, names_on_disk: list[str]) -> list[str]:
    """Return names_on_disk reordered per CHART_ORDER, with unknown
    charts appended at the end of their part."""
    canonical = CHART_ORDER.get(part, [])
    on_disk = [n for n in names_on_disk if n not in SKIP]
    seen: set[str] = set()
    out: list[str] = []
    for n in canonical:
        if n in on_disk and n not in seen:
            out.append(n)
            seen.add(n)
    for n in on_disk:
        if n not in seen:
            out.append(n)
            seen.add(n)
    return out


def sync_part(part: str) -> list[str]:
    src = PAPER_RESULTS / part / "figures"
    dst = DEST / part
    dst.mkdir(parents=True, exist_ok=True)
    for old in dst.glob("*.png"):
        old.unlink()
    on_disk = sorted(p.name for p in src.glob("*.png"))
    names = _ordered(part, on_disk)
    for name in names:
        shutil.copy2(src / name, dst / name)
    return names


def write_markdown(parts_to_charts: dict[str, list[str]]) -> None:
    lines = [
        "# All Paper Charts",
        "",
        "Mirror of every figure currently in `analysis/paper/results/part_1/figures/`, `part_2/figures/`, and `part_3/figures/`. No prose — just charts. Order follows `paper/results/results.md`. Regenerated by `run.py`.",
        "",
        "---",
        "",
    ]
    for part, header in PARTS:
        lines.append(f"## {header}")
        lines.append("")
        for name in parts_to_charts.get(part, []):
            stem = Path(name).stem
            lines.append(f"### {name}")
            lines.append(f"![{stem}](figures/{part}/{name})")
            lines.append("")
        lines.append("---")
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    if lines[-1] == "---":
        lines.pop()
    MD_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    parts_to_charts: dict[str, list[str]] = {}
    total = 0
    for part, _ in PARTS:
        names = sync_part(part)
        parts_to_charts[part] = names
        print(f"{part}: copied {len(names)} PNGs")
        total += len(names)
    write_markdown(parts_to_charts)
    print(f"total: {total} PNGs synced into {DEST.relative_to(ROOT)}")
    print(f"wrote {MD_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
