"""Sync all paper figures into one place + regenerate all_paper_charts.md.

Mirrors each `analysis/paper/results/part_{1,2,3}/figures/` dir into
`analysis/exploratory/all_paper_charts/figures/part_{1,2,3}/` and rewrites
`all_paper_charts.md` so the chart list matches whatever PNGs are currently
in those source dirs. Run after any paper figure update.
"""

from __future__ import annotations

import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
PAPER_RESULTS = ROOT / "analysis" / "paper" / "results"
HERE = Path(__file__).resolve().parent
DEST = HERE / "figures"
MD_PATH = HERE / "all_paper_charts.md"

PARTS: tuple[tuple[str, str], ...] = (
    ("part_1", "Part 1 — Scale, Convergence, Growth"),
    ("part_2", "Part 2 — Characterization"),
    ("part_3", "Part 3 — Action"),
)


def sync_part(part: str) -> list[str]:
    src = PAPER_RESULTS / part / "figures"
    dst = DEST / part
    dst.mkdir(parents=True, exist_ok=True)
    for old in dst.glob("*.png"):
        old.unlink()
    names: list[str] = []
    for png in sorted(src.glob("*.png")):
        shutil.copy2(png, dst / png.name)
        names.append(png.name)
    return names


def write_markdown(parts_to_charts: dict[str, list[str]]) -> None:
    lines = [
        "# All Paper Charts",
        "",
        "Mirror of every figure currently in `analysis/paper/results/part_1/figures/`, `part_2/figures/`, and `part_3/figures/`. No prose — just charts. Regenerated by `run.py`.",
        "",
        "---",
        "",
    ]
    for part, header in PARTS:
        lines.append(f"## {header}")
        lines.append("")
        for name in parts_to_charts.get(part, []):
            stem = Path(name).stem
            lines.append(f"### {name}")
            lines.append(f"![{stem}](figures/{part}/{name})")
            lines.append("")
        lines.append("---")
        lines.append("")
    if lines[-1] == "":
        lines.pop()
    if lines[-1] == "---":
        lines.pop()
    MD_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    parts_to_charts: dict[str, list[str]] = {}
    total = 0
    for part, _ in PARTS:
        names = sync_part(part)
        parts_to_charts[part] = names
        print(f"{part}: copied {len(names)} PNGs")
        total += len(names)
    write_markdown(parts_to_charts)
    print(f"total: {total} PNGs synced into {DEST.relative_to(ROOT)}")
    print(f"wrote {MD_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
